services:
  zacp:
    image: helloz/zacp
    container_name: zacp
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8680:8680"
    volumes:
      - ./data:/app/data
      - ./data/work:/app/data/work