/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./components/shell/AppSidebar.vue')['default']
    ChatPane: typeof import('./components/chat/ChatPane.vue')['default']
    Composer: typeof import('./components/chat/Composer.vue')['default']
    FileExplorer: typeof import('./components/files/FileExplorer.vue')['default']
    FilePanel: typeof import('./components/files/FilePanel.vue')['default']
    LocaleSwitch: typeof import('./components/LocaleSwitch.vue')['default']
    MessageItem: typeof import('./components/chat/MessageItem.vue')['default']
    MessageList: typeof import('./components/chat/MessageList.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NewSessionPane: typeof import('./components/chat/NewSessionPane.vue')['default']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NProgress: typeof import('naive-ui')['NProgress']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NTree: typeof import('naive-ui')['NTree']
    PermissionModal: typeof import('./components/chat/PermissionModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionListItem: typeof import('./components/shell/SessionListItem.vue')['default']
    SettingsDrawer: typeof import('./components/shell/SettingsDrawer.vue')['default']
    SidebarSessionList: typeof import('./components/shell/SidebarSessionList.vue')['default']
    ToolCallCard: typeof import('./components/chat/ToolCallCard.vue')['default']
    UserFooter: typeof import('./components/shell/UserFooter.vue')['default']
    WelcomeHero: typeof import('./components/chat/WelcomeHero.vue')['default']
  }
}
