/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSettings: typeof import('./components/shell/AboutSettings.vue')['default']
    AgentSettings: typeof import('./components/shell/AgentSettings.vue')['default']
    AppSidebar: typeof import('./components/shell/AppSidebar.vue')['default']
    ChatPane: typeof import('./components/chat/ChatPane.vue')['default']
    Composer: typeof import('./components/chat/Composer.vue')['default']
    DirectoryPicker: typeof import('./components/shell/DirectoryPicker.vue')['default']
    FileExplorer: typeof import('./components/files/FileExplorer.vue')['default']
    FilePanel: typeof import('./components/files/FilePanel.vue')['default']
    LocaleSwitch: typeof import('./components/LocaleSwitch.vue')['default']
    MessageItem: typeof import('./components/chat/MessageItem.vue')['default']
    MessageList: typeof import('./components/chat/MessageList.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NewSessionPane: typeof import('./components/chat/NewSessionPane.vue')['default']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NProgress: typeof import('naive-ui')['NProgress']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NTree: typeof import('naive-ui')['NTree']
    PermissionModal: typeof import('./components/chat/PermissionModal.vue')['default']
    PlanCard: typeof import('./components/chat/PlanCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionInfo: typeof import('./components/files/SessionInfo.vue')['default']
    SessionListItem: typeof import('./components/shell/SessionListItem.vue')['default']
    SettingsModal: typeof import('./components/shell/SettingsModal.vue')['default']
    SidebarSessionList: typeof import('./components/shell/SidebarSessionList.vue')['default']
    SystemSettings: typeof import('./components/shell/SystemSettings.vue')['default']
    ToolCallCard: typeof import('./components/chat/ToolCallCard.vue')['default']
    UserFooter: typeof import('./components/shell/UserFooter.vue')['default']
    WelcomeHero: typeof import('./components/chat/WelcomeHero.vue')['default']
  }
}
